--Cau1
SELECT MADATPHONG, MADV, SOLUONG
FROM CHI_TIET_SU_DUNG_DV
WHERE SOLUONG > 3 AND SOLUONG < 10;

--Cau2
UPDATE PHONG
SET GIAPHONG = GIAPHONG + 10.000
WHERE SOKHACHTOIDA > 10

--Cau3
DELETE FROM DAT_PHONG 
WHERE TRANGTHAIDAT = 'DA HUY'

--Cau4
SELECT TENKH
FROM KHACH_HANG
WHERE TENKH LIKE '[HNM]%' and LEN(TENKH) <= 20

--Cau5
   --Cach1
SELECT DISTINCT TENKH 
FROM KHACH_HANG
   --Cach2
SELECT TENKH from KHACH_HANG GROUP BY TENKH

--Cau6
SELECT MADV, TENDV, DONVITINH, DONGIA
FROM DICH_VU_DI_KEM 
WHERE ( DONVITINH LIKE 'LON' AND DONGIA > 10 ) OR ( DONVITINH LIKE 'CAI' AND DONGIA < 5)

--Cau7
SELECT dp.MADATPHONG, dp.MAPHONG, p.LOAIPHONG, p.SOKHACHTOIDA, p.GIAPHONG, kh.MAKH, kh.TENKH, kh.SODT, dp.NGAYDAT, dp.GIOBATDAU, dp.GIOKETTHUC, dv.MADV, ct.SOLUONG, dv.DONGIA
FROM DAT_PHONG dp
JOIN KHACH_HANG kh
on dp.MAKH = kh.MAKH 
JOIN PHONG p
on dp.MAPHONG = p.MAPHONG 
JOIN CHI_TIET_SU_DUNG_DV ct
ON dp.MADATPHONG = ct.MADATPHONG
JOIN DICH_VU_DI_KEM dv
ON ct.MADV = dv.MADV
WHERE (YEAR(NGAYDAT) = 2016 OR YEAR(NGAYDAT) = 2017) AND P.GIAPHONG > 50.000

--Cau8 CHƯA XONG
SELECT DAT_PHONG.MADATPHONG, DAT_PHONG.MAPHONG, PHONG.LOAIPHONG, PHONG.GIAPHONG, KHACH_HANG.TENKH, DAT_PHONG.NGAYDAT,(PHONG.GIAPHONG * (DAT_PHONG.GIOKETTHUC - DAT_PHONG.GIOBATDAU)) AS TONGTIENMAT
FROM DAT_PHONG
JOIN PHONG ON DAT_PHONG.MAPHONG = PHONG.MAPHONG
JOIN KHACH_HANG ON DAT_PHONG.MAKH = KHACH_HANG.MAKH
LEFT JOIN CHI_TIET_SU_DUNG_DV ON CHI_TIET_SU_DUNG_DV.MADATPHONG = DAT_PHONG.MADATPHONG
LEFT JOIN DICH_VU_DI_KEM ON DICH_VU_DI_KEM.MADV = CHI_TIET_SU_DUNG_DV.MADV 
GROUP BY DAT_PHONG.MADATPHONG

--Cau9
SELECT DISTINCT kh.MaKH, kh.TenKH, kh.DiaChi, kh.SoDT
FROM KHACH_HANG kh
INNER JOIN DAT_PHONG dp ON kh.MaKH = dp.MaKH
INNER JOIN PHONG p ON dp.MaPhong = p.MaPhong
WHERE kh.DIACHI LIKE '%Hoa Xuan%'



